using UnityEngine;

public class WeaponCollider : MonoBehaviour
{
    [Header("Som da arma")]
    public UnityEngine.AudioSource audioSource;   // Arraste o AudioSource da arma aqui
    public AudioClip somBatida;       // Som do metal batendo no ch達o

    [Header("Layer do ch達o")]
    public string chaoLayerName = "Chao";  // Nome do layer do ch達o

    private bool tocouChao = false;

    void OnCollisionEnter2D(Collision2D collision)
    {
        if (!tocouChao && collision.gameObject.layer == LayerMask.NameToLayer(chaoLayerName))
        {
            tocouChao = true;
            if (audioSource != null && somBatida != null)
                audioSource.PlayOneShot(somBatida);
        }
    }

    void OnCollisionExit2D(Collision2D collision)
    {
        // Quando a arma sair do ch達o, permite tocar som novamente
        if (collision.gameObject.layer == LayerMask.NameToLayer(chaoLayerName))
        {
            tocouChao = false;
        }
    }
}